steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '--build-arg', 'VERSION=$TAG_NAME', 
      '--build-arg', 'COMMIT_SHA=$COMMIT_SHA', 
      '--build-arg', 'BUILD_DATE=$(date -u +"%Y-%m-%d")', 
      '-t', 'gcr.io/$PROJECT_ID/elastic-diagram-maker:$COMMIT_SHA', 
      '.'
    ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/elastic-diagram-maker:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'elastic-diagram-maker',
      '--image', 'gcr.io/$PROJECT_ID/elastic-diagram-maker:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'VERSION=$TAG_NAME,COMMIT_SHA=$COMMIT_SHA,BUILD_DATE=$(date -u +"%Y-%m-%d")'
    ]

images:
  - 'gcr.io/$PROJECT_ID/elastic-diagram-maker:$COMMIT_SHA'

substitutions:
  _SERVICE_NAME: elastic-diagram-maker
  _REGION: us-central1
